version: '3.1'
services:
  odoo:
    image: odoo:16.0
    container_name: odoo
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '8069:8069'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '5050:80'
    networks:
      - postgres
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  postgres:
    driver: bridge
